<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Racing Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'fjtarud@extremaxcorp.com',
		'to' => 'fjtarud@extremaxcorp.com'
	),
	'fields' => array(
		'custom_U1842' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Age',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Age\' is required.',
				'format' => 'Field \'Age\' has an invalid email.'
			)
		),
		'custom_U1869' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Racing Number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Racing Number\' is required.'
			)
		),
		'custom_U1854' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Location',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Location\' is required.'
			)
		),
		'custom_U1873' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'eMail',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'eMail\' is required.'
			)
		),
		'custom_U1981' => array(
			'order' => 6,
			'type' => 'checkboxgroup',
			'label' => 'Racing Course',
			'required' => true,
			'optionItems' => array(
				'Sport Driving Course',
				'Corsa Driving Course'
			),
			'errors' => array(
				'required' => 'Field \'Racing Course\' is required.',
				'format' => 'Field \'Racing Course\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
